template_path: app-extra-certificate.yaml
stack_name: synapse-login-scipoolprod-extra
dependencies:
  - prod/synapse-login-scipoolprod.yaml
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  Listener443Arn: "arn:aws:elasticloadbalancing:us-east-1:237179673806:listener/app/awseb-AWSEB-GFSO0GTC8UY2/ecfe9b49dab884b5/3731edc80a584ae2"
  CertificateArn: !stack_output_external synapse-login-scipoolprod-sageit-cert::SSLCertificateSageIT
