template_path: app-extra-certificate.yaml
stack_name: synapse-login-strides-extra
dependencies:
  - strides/synapse-login-strides.yaml
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  Listener443Arn: "arn:aws:elasticloadbalancing:us-east-1:423819316185:listener/app/awseb-AWSEB-WA85KZ8T07CD/db78aedcc9d399a4/7ab27214720751b9"
  CertificateArn: !stack_output_external synapse-login-strides-sageit-cert::SSLCertificateSageIT
