template_path: app-extra-certificate.yaml
stack_name: synapse-login-bmgfki-extra
dependencies:
  - bmgfki/synapse-login-bmgfki.yaml
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  Listener443Arn: "arn:aws:elasticloadbalancing:us-east-1:464102568320:listener/app/awseb-AWSEB-19RY2RJRIE8Y8/d53373834f4bcc66/c8b80b5beb1d43aa"
  CertificateArn: !stack_output_external synapse-login-bmgfki-sageit-cert::SSLCertificateSageIT
