template_path: app.yaml
stack_name: synapse-login-scipooldev
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
depedencies:
  - develop/synapse-login-scipooldev-params.yaml
  - develop/synapse-login-scipooldev-base.yaml
parameters:
  AppDeployBucketName: "org-sagebase-scipooldev-synapse-login-scipooldev"
  SnsBounceNotificationEndpoint: "aws.scipooldev@sagebase.org"
  SnsNotificationEndpoint: "aws.scipooldev@sagebase.org"
  DNSHostname: "synapse-login-scipooldev"
  DNSDomain: "scipooldev.org"
  EC2InstanceType: "t3.small"
  EC2KeyName: 'scipool'
  VpcName: "cesspoolvpc"
  AutoScalingMinSize: "1"
  AutoScalingMaxSize: "2"
  RollingUpdateType: "Health"
  OidcClientSecretKeyName: "/service-catalog/SynapseOauthClientSecret"
  SsmParameterPrefix: !stack_output_external synapse-login-scipooldev-params::Prefix
  SolutionStackName: "64bit Amazon Linux 2 v4.10.0 running Tomcat 9 Corretto 8"
